### ISSUE TITLE
requestTimeout

### ISSUE THREAD

**Issue by kkenwort** [cnect/sails-sqlserver#13]
There is no way to configure request timeout from connections.js.  I tried using the config property 'timeout' to increase the request timeout value, but that does not work.  Adding requestTimout: config requestTimeout to the adapter.js marshalConfig method passes the property to the mssql layer and adjusts the timeout value.   Consider adding this and the other mssql config properties so they can be set in connections.js.

Thanks,
Kevin

**Comment by tjwebb** [comment]
I actually just ran into this yesterday and I'll have a fix out soon.

**Comment by kkenwort** [comment]
I forgot to tell you thanks for your work with this module.  I’m finding it very useful. 

Thanks,
Kevin
