### ISSUE TITLE
Not compatible with waterline 10.17+

### ISSUE THREAD

**Issue by keeganmccallum** [cnect/sails-sqlserver#24]
On sails@0.11.0 the adapter does not properly integrate with waterline. I was previously using the adapter without issue on sails@0.11.0-rc8. The former uses "waterline": "~0.10.17" while the latter uses "waterline": "~0.10.11". I attempted to add a log statement into the find method of the adapter, which on the earlier version gets called and the query properly returns the results, but, on the newer version, the adapter method is never called and I am just returned an empty array.

**Comment by tjwebb** [comment]
I need a stack trace, code examples, some sort of other details that would help me diagnose this.

**Comment by keeganmccallum** [comment]
Model.find().exec(function (err, instances) {console.log(err, instances)});

Call the above code in bootstrap.js, with a pre-populated model. Try first with npm install sails@0.11.0-rc8, the code should work, the console should show "null, [YOUR INSTANCES HERE]". Then run npm install sails@0.11.0, and you will see that with no other changes, the console will now show "null, []". 

If you dive into your adapter.js file and add some log statements into your find definition, you will see that the function is called on the first sails version, but not on the second. 

There is no errors shown, so there is no stacktrace I can give you. Just fails silently.

**Comment by keeganmccallum** [comment]
Further information about env: 

Windows 7, node.js version v0.12.2, SQL Server 2005. Looking at the adapter code, at first glance I cannot see why it wouldn't working, seems strange but it appears it is not even being applied to the connection. I swapped in sails-disk and sails-redis, and they work without issue but for some reason this adapter isn't working with later versions of sails/waterline.

**Comment by keeganmccallum** [comment]
Issue appears to be with needing to define the connection in models.js in sails config on sails@0.11.0+, not with this adapter specifically. Will investigate further and possibly raise an issue with sails/waterline.
