### ISSUE TITLE
Max 30 records

### ISSUE THREAD

**Issue by alexandrepage** [cnect/sails-sqlserver#29]
Hi, when I use the adapter. It seems it can only returns maximum 30 records, using the sails built-in rest API. I tried to change to pool.max config for the connection, but there is no change. Is there a way to make the max number of record to unlimited, or at least higher that 30 ?

**Comment by amit-kumawat** [comment]
Try to increase the limit in config\blueprints.js

// defaultLimit: 30

**Comment by alexandrepage** [comment]
Thanks man :)
