### ISSUE TITLE
Does this work on heroku?

### ISSUE THREAD

**Issue by laicosly** [cnect/sails-sqlserver#34]
I've got it working locally on a mac, but requests timeout on heroku, without any additional error information.

Is there additional setup for heroku, such as a buildpack?

**Comment by tjwebb** [comment]
I don't know what this means. You haven't provided any info that would help me diagnose your problem.

**Comment by laicosly** [comment]
I'm wondering if there are pre-requisites or requirements on the operating system for this to work.  Such as a TDS driver.  Since asking the question, I discovered that mssql is a dependency, and it's readme mentions requiring a TDS driver.

Have you deployed your sqlserver module to heroku with success?  Did you need to include anything else such as a heroku buildpack for a tds driver?

**Comment by tjwebb** [comment]
Yea, I've run this on heroku (in fact there's an app running it on heroku right now). The tds driver used is pure javascript, and there are no OS dependencies.

If you can provide more info on the actual error you're experiencing, I might be able to help.

**Comment by laicosly** [comment]
If I could provide further info to help you diagnose the issue I would, but plainly the sails orm methods using sqlserver just time out on heroku without any other information.  Yet it works on my local machine.  I have nothing else at this time.

**Comment by tjwebb** [comment]
> just time out on heroku without any other information

So there are no errors in the heroku logs? Any info in your sqlserver logs? Any code you can share? Configuration? any issues in the heroku build logs? Can you confirm that the connection is actually established with the sqlserver?

**Comment by laicosly** [comment]
the heroku error is a timeout.  I'll check sqlserver logs tomorrow.  Heroku builds fine, the rest of sailsjs is working as expected.  I'm not positive how to confirm the connection is established.  I've just encountered this, will report back as soon as I have more to share.

**Comment by laicosly** [comment]
SQL Server Firewall!
