### ISSUE TITLE
Unbundle mssql 

### ISSUE THREAD

**Issue by amyspark** [cnect/sails-sqlserver#35]
The currently published version of `sails-sqlserver` (0.10.8) includes `mssql` 2.1.3.
This version prevents me from connecting to an Azure SQL database v12, because of  https://github.com/pekim/tedious/issues/262.

I am currently using as override:

``` javascript
    "sails-sqlserver": {
      "version": "0.10.8",
      "from": "sails-sqlserver@~0.10.8",
      "dependencies": {
        "mssql": {
          "version": "2.3.1",
          "from": "mssql@~2.3.1"
        }
      }
    }
```

**Comment by deluxor** [comment]
Yes, it happened to me the same :/ , I was trying to connect to a SQL DB on azure from an azure VM and it won't connect, and I was WTF is happening??? I cannot connect even inside the azure? When i checked the opened connections with `lsof -i` I saw this evil vision, connection hangs on SYN at port 11184:

`node      37735    root   30u  IPv4 1007914      0t0  TCP 10.4.0.4:44319->191.237.232.75:11184 (SYN_SENT)
node      37735    root   31u  IPv4 1007915      0t0  TCP 10.4.0.4:44320->191.237.232.75:11184 (SYN_SENT)
node      37735    root   32u  IPv4 1007916      0t0  TCP 10.4.0.4:44321->191.237.232.75:11184 (SYN_SENT)
node      37735    root   33u  IPv4 1007917      0t0  TCP 10.4.0.4:44322->191.237.232.75:11184 (SYN_SENT)
node      37735    root   34u  IPv4 1007918      0t0  TCP 10.4.0.4:44323->191.237.232.75:11184 (SYN_SENT)
node      37735    root   35u  IPv4 1007919      0t0  TCP 10.4.0.4:44324->191.237.232.75:11184 (SYN_SENT)`

Please update the dependencies :)

**Comment by ThomasDelteil** [comment]
@deluxor even when upgrading mssql to 2.3.1 manually, I still get
```
Error: The hook `orm` is taking too long to load.
Make sure it is triggering its `initialize()` callback, or else set `sails.config.orm._hookTimeout to a higher value (currently 20000)
```
When trying to connect to a MSSQL DB from Azure VM (works fine from local)
Did you manage to make it work in the end?

**Comment by deluxor** [comment]
@ThomasDelteil Hello friend, yes I made it working, and works completely fine!

Here is the package.json inside of sails-sqlserver module in node_modules:

```
"dependencies": {
    "captains-log": "^0.11.11",
    "lodash": "^3.8.0",
    "mssql": "2.3.1",
    "underscore.string": "^3.0.0",
    "waterline-cursor": "0.0.5"
  }
```

**Comment by ThomasDelteil** [comment]
@deluxor thanks! I actually made it working by pinning the dependency to this fork https://github.com/cwfa/sails-sqlserver in my package.json.
I think it might be better to do it that way because otherwise you would lose your changes everytime you clone the repo, except if you checkin all your node dependencies.. Or maybe you could modify the way you propose and then create a shrinkwrap.
