### ISSUE TITLE
documentation says npm install sails-sqlserver-adapter --save which is wrong

### ISSUE THREAD

**Issue by paulvanbladel** [cnect/sails-sqlserver#5]
should be, as far as I understand,
npm install sails-sqlserver --save

NPM can't find sails-sqlserver-adapter.

32 error 404 'sails-sqlserver-adapter' is not in the npm registry.

**Comment by tjwebb** [comment]
fixes #2

**Comment by tjwebb** [comment]
Yes, you're correct. I will fix this this evening. The module was renamed to sails-sqlserver.

**Comment by tjwebb** [comment]
Should be correct now.
