### ISSUE TITLE
Support for trusted connections?

### ISSUE THREAD

**Issue by davepreston** [cnect/sails-sqlserver#7]
I used sails-mssql in the past, but on my latest project was wanting to switch to this module because sails-mssql was deprecated.
  
  My question is around trusted connections. They don't seem to work anymore and I'm hoping that's something that is in the works. I don't want to put my user/password into a configuration file (or even an environment variable).

It looks like the switch from `node-sqlserver` to `mssql` is when we lost support for trusted connections, but I'm hoping I'm missing something.

**Comment by tjwebb** [comment]
I'm not sure; as far as I know, we haven't used anything but mssql for awhile.

Can you provide some more details on how this feature should work? Thanks

**Comment by davepreston** [comment]
The version I used in the past was @swelham I believe that was forked by @jaredfromsubway which this repo forked. (I looked back and I believe that only swelham was using node-sqlserver). mssql seems to have split out the Trusted Connection feature into a separate repo, but I'm unclear on the details.

Here's the old readme that has a section on connecting.
https://github.com/swelham/sails-mssql/blob/dd39a226ec3b79a40612d72f2028f3d5ec1fa9a6/README.md

```
module.exports.adapters = {
  'default': 'mssql',
  mssql: {
    module: 'sails-mssql',
    connectionString: 'Driver=SQL Server Native Client 11.0;Server=Your Server;Database=Your Database;Trusted_Connection=Yes'
  }
};
```
The benefit of this was that when running on windows, integrated authentication would allow the database connection as the user who was running the node process (assuming they had DB privileges) without specifying user/password.

**Comment by SyntaxRules** [comment]
:+1: For handling windows integrated security

**Comment by tjwebb** [comment]
> Trusted_Connection=Yes

So you're saying this part of the connection string no longer has any effect due to lack of support in `mssql`?

**Comment by davepreston** [comment]
I'm not 100% clear, but it's my understanding that mssql relies on other modules to connect, but the native windows Microsoft Driver (that uses the connection string technique) is not installed by default. 
More details here: https://github.com/patriksimek/node-mssql#cfg-msnodesql

**Comment by tjwebb** [comment]
This adapter is never going to include any compiled binaries by default.

You can pass additional config settings in a `config` object as with most adapters. If you have the native driver installed, maybe you can connect it up to mssql this way.

**Comment by davepreston** [comment]
Fair enough. I'll do a little more digging, but I think I'll have to avoid using Trusted Connections.

**Comment by tjwebb** [comment]
If there's a way to support this without including compiled binaries, I'd love to have this feature.
