### ISSUE TITLE
Error when connect to sql server 64 bits

### ISSUE THREAD

**Issue by alejandropaciotti** [cnect/sails-sqlserver#9]
I tried to use this library with two different sql server versions, a 32-bit version 10.50.1600 and a 64-bit  10.0.5520 bits.

The first is perfectly connected.

With the release of 64-bit sql server there is no way to get it connected.

However, if I use the mssql library, connects perfectly! (https://github.com/patriksimek/node-mssql)

I have seen that this library uses version 10 of tedious.

Maybe that's the problem.

Although my knowledge is not very deep, I'll try to fix the problem.

**Comment by tjwebb** [comment]
What version of sql server is this?

**Comment by alejandropaciotti** [comment]
The version is 2008R2 64-BIT, but I'm a bit puzzled because just installed on my PC a version 2008 32-BIT and gives me the same problem.

I think there must be a configuration problem on my Windows installation because  I can connect to other servers with sqlserver 2005/2008.

The ports are open, the firewall disabled, and indeed, with mssql library I can connect perfectly with the following code:

``` js
var sql      = require('mssql'); 

var database = {
     server:'192.168.1.102',  
     port:1450,
     database: 'SACC',
     user: 'myuser',
     password: 'mypassword'
 }

var connection = new sql.Connection(database, function(err) {
	 		 var sql_request = new sql.Request(connection); 
			 
			 sql_request.query('SELECT * FROM oneTable', function(err, resultSet) {
			 		if(err) throw err;
			 		console.log(resultSet);
			 	});
			})		
```

Anyway, if there is any way to debug, let me know please.


This is the error message:

``` js
debug: --------------------------------------------------------
{ [ConnectionError: Failed to connect to 192.168.1.102:1450 in 15000ms]
  name: 'ConnectionError',
  message: 'Failed to connect to 192.168.1.102:1450 in 15000ms',
  code: 'ETIMEOUT' }
error: Sending 500 ("Server Error") response: 
 Error (E_UNKNOWN) :: Encountered an unexpected error
ConnectionError: Failed to connect to 192.168.1.102:1450 in 15000ms
    at Connection.<anonymous> (/home/ubuntu/Proyectos/backEnd/node_modules/sails-sqlserver/node_modules/mssql/lib/tedious.js:320:25)
    at Connection.g (events.js:199:16)
    at Connection.emit (events.js:107:17)
    at Connection.connectTimeout (/home/ubuntu/Proyectos/backEnd/node_modules/sails-sqlserver/node_modules/mssql/node_modules/tedious/lib/connection.js:709:10)
    at null._onTimeout (/home/ubuntu/Proyectos/backEnd/node_modules/sails-sqlserver/node_modules/mssql/node_modules/tedious/lib/connection.js:3:59)
    at Timer.listOnTimeout (timers.js:110:15)

Details:  ConnectionError: Failed to connect to 192.168.1.102:1450 in 15000ms

```

**Comment by toledosteve** [comment]
I'm actually running into the same problem with SQL Server 2008R2 64 bit.  The connection works fine with unixODBC and freetds version 7_1, but the default tedious.js uses 7_4 so I'm wondering if it's due to that.  I'd like to get the issue corrected and offer up a pull request as I have immediate need in getting this to work.

**Comment by toledosteve** [comment]
Actually, I stand corrected.  My installed version of sails-sqlserver was version 0.10.4 and it was timing out but I updated the package to 0.10.7 and it connected perfectly.  @alejandropaciotti What version of sails-sqlserver are you using?

**Comment by tjwebb** [comment]
In that case, I think this issue is related to #13 and #14.
